### ISSUE TITLE
Matlab 2018b with Linux

### ISSUE THREAD

**Issue by syachroel** [goGPS-Project/goGPS_MATLAB#62] opened 2019-03-08 11:37 UTC
Dear Dr Gati...

 I try run goGPS new update... in another PC used Linux 16.04 with matlab 2018b 
but my result....

_Dot indexing is not supported for variables of this type.

Error in Core_Utils.readAntennaPCV (line 354)
                                                        if ~(date_limits.first.getMatlabTime()
                                                        > datenum(validity_start) &&
                                                        (date_limits.last.getMatlabTime() <
                                                        datenum(validity_end)))

Error in Core_Sky/loadAntPCV (line 1964)
            this.ant_pcv = Core_Utils.readAntennaPCV(filename_pcv, this.cc.getAntennaId(),
            this.time_ref_coord);

Error in Core_Sky/initSession (line 184)
                this.loadAntPCV(Core.getState.getAtxFile);

Error in Core/initSkySession (line 884)
                this.sky.initSession(time_lim.first, time_lim.last);

Error in Core/prepareSession (line 858)
                        this.initSkySession(time_lim_large);

Error in Command_Interpreter/exec (line 722)
                                    is_empty = core.prepareSession(s);

Error in Core/exec (line 920)
            this.cmd.exec(this, cmd_list);

Error in Core/go (line 905)
            this.exec(this.state.cmd_list);

Error in goGPS (line 137)
            core.go(); % execute all_

I dont have any idea...

Thanks

**Comment by clicat** [comment] 2019-03-09 06:56
Hi, I’m on holiday and far from home till Sunday. On Monday I’ll have a look at it.
1. There is a missing check on the existence of the antex file
2. It seems that the antenna haven’t been loaded: this could due to 2 possible problems, the first is that I broke the code (very probable with my last rushed update on the parallelism), the second is that the antex (.ATX) file doesn't exist (in a case sensitive way.

As I said, on Monday I’ll debut the code ;-)

**Comment by syachroel** [comment] 2019-03-09 06:58
Sorry....,okay I'm waiting on Monday

**Comment by clicat** [comment] 2019-03-19 13:14
Hi @syachroel sorry if I didn't answer I was too busy, I tried to reproduce the bug with no success, could you attach the antex (.ATX) file you were trying to load?

**Comment by clicat** [comment] 2019-08-16 13:56
with no updates since March, I'm closing this bug

**Closed as completed** 2019-08-17 18:15 UTC

**Comment by kazimz** [comment] 2020-11-19 20:44
Hi Andrea,
I am facing exactly the same issue. Kindly have a look. Thanks
ATX file attached. 
[I14.zip](https://github.com/goGPS-Project/goGPS_MATLAB/files/5569567/I14.zip)
Best Regards
Ali
